mem2reg crash 6:6:20: the loop was declared with breaks or returns but they are all unreachable
main := fn(): uint loop if false return blackbox()
                   ^